# Generated by Django 5.1 on 2024-09-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallary', 'verbose_name_plural': 'product gallary'},
        ),
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
